version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      gtk-rs:
        patterns:
          - "gtk4*"
          - "gdk4*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
