# Type Path Mode User Group Age Argument
d /var/log/am5-spd-diag 2775 root users -
d /var/log/am5-spd-diag/events 2775 root users -
d /var/log/am5-spd-diag/reports 2775 root users -
d /var/log/am5-spd-diag/packages 2775 root users -
d /var/log/am5-spd-diag/latest 2775 root users -
